config/routes.rb
OpensipsWac::Application.routes.draw do

  resources :translations

  devise_for :users#, :controllers => { :sessions => "users/sessions" }
  devise_for :admins#, :controllers => { :sessions => "admins/sessions" }

  root :to => 'translations#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/translation.rb
class Translation < ActiveRecord::Base
  attr_accessible :from_domain, :from_username, :match_regex, :tran_add_header, :tran_domain, :tran_prefix, :tran_priority, :tran_strip, :tran_user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!
  protect_from_forgery
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  # GET /translations
  # GET /translations.json
  def index
    @translations = Translation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @translations }
    end
  end

  # GET /translations/1
  # GET /translations/1.json
  def show
    @translation = Translation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @translation }
    end
  end

  # GET /translations/new
  # GET /translations/new.json
  def new
    @translation = Translation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @translation }
    end
  end

  # GET /translations/1/edit
  def edit
    @translation = Translation.find(params[:id])
  end

  # POST /translations
  # POST /translations.json
  def create
    @translation = Translation.new(params[:translation])

    respond_to do |format|
      if @translation.save
        format.html { redirect_to translations_url, notice: 'Translation was successfully created.' }
        format.json { render json: @translation, status: :created, location: @translation }
      else
        format.html { render action: "new" }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /translations/1
  # PUT /translations/1.json
  def update
    @translation = Translation.find(params[:id])

    respond_to do |format|
      if @translation.update_attributes(params[:translation])
        format.html { redirect_to translations_url, notice: 'Translation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translations/1
  # DELETE /translations/1.json
  def destroy
    @translation = Translation.find(params[:id])
    @translation.destroy

    respond_to do |format|
      format.html { redirect_to translations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "OpenSIPS WAC", root_path, :class => 'brand' %>
<ul class="nav">
  <li>
    <%= link_to 'Translations', translations_path %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : 'OpenSIPS WAC' %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "opensips-wac" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/translations/_form.html.haml
.row
  .span3.offset4
    = simple_form_for @translation, :html => {:class => 'well'} do |f|
      = f.error_notification
      .inputs
        .control-group
          .controls
            = f.input :from_domain, :label => 'From Domain'
            = f.input :from_username, :label => 'From Username'
            = f.input :match_regex, :label => 'Match Regex'
            = f.input :tran_add_header, :label => 'Tran Add Header'
            = f.input :tran_domain, :label => 'Tran Domain'
            = f.input :tran_prefix, :label => 'Tran Prefix'
            = f.input :tran_priority, :label => 'Tran Priority'
            = f.input :tran_strip, :label => 'Tran Strip'
            = f.input :tran_user, :label => 'Tran User'
      .actions
        .control-group
          .controls
            = f.button :submit, 'Save', :class => 'btn btn-primary'

app/views/translations/edit.html.haml
%fieldset
  %legend
    Editing Translation

  = render 'form'

  =# link_to 'Show', @translation, :class => 'btn'
  =# link_to 'Back', translations_path

app/views/translations/index.html.haml
%h3 Translations

%table.table.table-striped.table-hover
  %tr
    %th ID
    %th From Domain
    %th From Username
    %th Match Regex
    %th Tran Add Header
    %th Tran Domain
    %th Tran Prefix
    %th Tran Priority
    %th Tran Strip
    %th Tran User
    %th Actions

  - @translations.each do |translation|
    %tr
      %td= translation.id
      %td= translation.from_domain
      %td= translation.from_username
      %td= translation.match_regex
      %td= translation.tran_add_header
      %td= translation.tran_domain
      %td= translation.tran_prefix
      %td= translation.tran_priority
      %td= translation.tran_strip
      %td= translation.tran_user
      %td
        %ul.actions
          %li= link_to 'Edit', edit_translation_path(translation), :class => 'btn btn-mini'
          %li= link_to 'Destroy', translation, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger btn-mini'

%br

= link_to 'New Translation', new_translation_path, :class => 'btn'

app/views/translations/new.html.haml
%fieldset
  %legend
    New Translation

  = render 'form'

  =# link_to 'Back', translations_path

app/views/translations/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_translation_path(@translation), :class => 'btn'
=# link_to 'Back', translations_path

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>